# tech_words.py — эталонная база технических терминов и команд для autoswitch.
# Подмешивается в английский словарь, чтобы IT-текст (команды, утилиты, термины)
# корректно определялся и чинился в любой раскладке.
#
# ЭТО ЭТАЛОННЫЙ ФАЙЛ — не редактируется пользователем.
# Свои слова добавляй через: asc -> Тех-словарь -> Добавить (пишутся в user_words.txt).

TECH_WORDS = {
    # --- базовые команды Linux / GNU coreutils ---
    'ls', 'cd', 'pwd', 'cp', 'mv', 'rm', 'mkdir', 'rmdir', 'touch', 'cat', 'tac',
    'head', 'tail', 'less', 'more', 'echo', 'printf', 'test', 'true', 'false',
    'sort', 'uniq', 'wc', 'cut', 'paste', 'join', 'split', 'tr', 'tee', 'yes',
    'nl', 'od', 'fold', 'fmt', 'pr', 'expand', 'unexpand', 'comm', 'csplit',
    'basename', 'dirname', 'realpath', 'readlink', 'stat', 'file', 'type',
    'seq', 'shuf', 'factor', 'numfmt', 'date', 'cal', 'sleep', 'timeout', 'watch',
    'chmod', 'chown', 'chgrp', 'umask', 'ln', 'link', 'unlink', 'mktemp',
    'df', 'du', 'sync', 'truncate', 'shred', 'dd', 'install', 'mkfifo',
    # --- поиск и обработка текста ---
    'grep', 'egrep', 'fgrep', 'rgrep', 'ripgrep', 'ag', 'ack', 'sed', 'awk',
    'gawk', 'find', 'locate', 'updatedb', 'which', 'whereis', 'whatis', 'apropos',
    'xargs', 'diff', 'patch', 'cmp', 'sdiff', 'colordiff', 'jq', 'yq', 'fzf',
    'strings', 'hexdump', 'xxd', 'iconv', 'dos2unix', 'unix2dos', 'rev',
    # --- процессы и система ---
    'ps', 'top', 'htop', 'btop', 'atop', 'glances', 'iotop', 'iftop', 'nethogs',
    'kill', 'killall', 'pkill', 'pgrep', 'pidof', 'nice', 'renice', 'nohup',
    'jobs', 'bg', 'fg', 'disown', 'wait', 'exec', 'time', 'strace', 'ltrace',
    'lsof', 'fuser', 'vmstat', 'iostat', 'mpstat', 'sar', 'free', 'uptime',
    'uname', 'hostname', 'hostnamectl', 'arch', 'nproc', 'lscpu', 'lsmem',
    'dmesg', 'sysctl', 'ulimit', 'getconf', 'chroot', 'nsenter', 'unshare',
    # --- systemd / службы ---
    'systemctl', 'systemd', 'service', 'journalctl', 'systemd-analyze',
    'loginctl', 'timedatectl', 'localectl', 'busctl', 'coredumpctl', 'networkctl',
    'init', 'telinit', 'runlevel', 'cron', 'crontab', 'anacron', 'at', 'batch',
    'daemon', 'daemonize', 'supervisor', 'supervisord',
    # --- пользователи и права ---
    'sudo', 'su', 'doas', 'passwd', 'chpasswd', 'useradd', 'userdel', 'usermod',
    'groupadd', 'groupdel', 'groupmod', 'gpasswd', 'newgrp', 'whoami', 'who',
    'id', 'groups', 'w', 'last', 'lastlog', 'users', 'finger', 'chage', 'visudo',
    'login', 'logout', 'exit', 'logname',
    # --- архивы и сжатие ---
    'tar', 'gzip', 'gunzip', 'zcat', 'bzip', 'bzip2', 'bunzip2', 'xz', 'unxz',
    'zstd', 'lz4', 'zip', 'unzip', 'rar', 'unrar', 'p7zip', 'compress', 'cpio',
    'ar', 'pigz', 'lzma', 'lzop', 'archive', 'extract', 'compress',
    # --- сеть ---
    'ssh', 'sshd', 'scp', 'sftp', 'rsync', 'ftp', 'tftp', 'telnet', 'nc', 'ncat',
    'netcat', 'socat', 'curl', 'wget', 'aria', 'axel', 'ping', 'ping6', 'fping',
    'traceroute', 'tracepath', 'mtr', 'nslookup', 'dig', 'host', 'whois',
    'ifconfig', 'iwconfig', 'iproute', 'route', 'arp', 'arping', 'ethtool',
    'netstat', 'ss', 'nmap', 'masscan', 'zmap', 'tcpdump', 'tshark', 'wireshark',
    'iptables', 'nftables', 'ufw', 'firewalld', 'firewall', 'ipset', 'conntrack',
    'nmcli', 'nmtui', 'wpa', 'wpasupplicant', 'hostapd', 'dnsmasq', 'bind',
    'dhclient', 'dhcpcd', 'resolvectl', 'systemd-resolved', 'avahi', 'mdns',
    'openvpn', 'wireguard', 'ipsec', 'strongswan', 'openconnect', 'sslstrip',
    # --- git и VCS ---
    'git', 'gitk', 'gitui', 'lazygit', 'tig', 'svn', 'mercurial', 'bazaar',
    'clone', 'commit', 'push', 'pull', 'fetch', 'merge', 'rebase', 'branch',
    'checkout', 'switch', 'restore', 'stash', 'cherry', 'reset', 'revert',
    'remote', 'origin', 'upstream', 'master', 'main', 'head', 'tag', 'blame',
    'diff', 'log', 'status', 'add', 'commit', 'init', 'clone', 'submodule',
    'repo', 'repository', 'fork', 'gist', 'github', 'gitlab', 'bitbucket',
    'pipeline', 'runner', 'workflow', 'action', 'webhook',
    # --- контейнеры / оркестрация ---
    'docker', 'dockerd', 'podman', 'buildah', 'skopeo', 'containerd', 'runc',
    'compose', 'swarm', 'kubernetes', 'kubectl', 'kubeadm', 'kubelet', 'minikube',
    'kind', 'helm', 'kustomize', 'rancher', 'openshift', 'nomad', 'consul',
    'container', 'image', 'volume', 'network', 'registry', 'dockerfile', 'pod',
    'deployment', 'namespace', 'ingress', 'configmap', 'secret', 'replica',
    'cluster', 'node', 'service', 'daemonset', 'statefulset', 'cronjob',
    # --- IaC / DevOps ---
    'terraform', 'ansible', 'puppet', 'chef', 'saltstack', 'vagrant', 'packer',
    'jenkins', 'gitlab', 'travis', 'circleci', 'drone', 'argocd', 'flux',
    'prometheus', 'grafana', 'loki', 'jaeger', 'zipkin', 'kibana', 'logstash',
    'elasticsearch', 'fluentd', 'telegraf', 'influxdb', 'nagios', 'zabbix',
    'vault', 'boundary', 'packer', 'provision', 'deploy', 'rollout', 'rollback',
    # --- пакетные менеджеры ---
    'apt', 'aptitude', 'dpkg', 'apget', 'yum', 'dnf', 'rpm', 'zypper', 'pacman',
    'yay', 'paru', 'aur', 'snap', 'snapd', 'flatpak', 'appimage', 'nix', 'guix',
    'brew', 'homebrew', 'macports', 'portage', 'emerge', 'xbps', 'apk', 'pkg',
    'pip', 'pipx', 'conda', 'poetry', 'pipenv', 'npm', 'yarn', 'pnpm', 'bun',
    'gem', 'bundler', 'cargo', 'composer', 'maven', 'gradle', 'sbt', 'nuget',
    'go', 'gomod', 'cpan', 'luarocks', 'opam', 'stack', 'cabal',
    # --- редакторы / IDE ---
    'nano', 'vim', 'neovim', 'nvim', 'vi', 'emacs', 'ed', 'micro', 'kakoune',
    'helix', 'gedit', 'kate', 'kwrite', 'mousepad', 'geany', 'code', 'vscode',
    'codium', 'sublime', 'atom', 'brackets', 'notepad', 'jetbrains', 'idea',
    'pycharm', 'webstorm', 'phpstorm', 'clion', 'goland', 'rider', 'fleet',
    'eclipse', 'netbeans', 'android', 'xcode', 'devkit',
    # --- языки программирования ---
    'python', 'python3', 'cpython', 'pypy', 'ruby', 'perl', 'php', 'lua', 'tcl',
    'node', 'nodejs', 'deno', 'bun', 'javascript', 'typescript', 'coffeescript',
    'java', 'kotlin', 'scala', 'groovy', 'clojure', 'golang', 'rust', 'cargo',
    'swift', 'objectivec', 'dart', 'flutter', 'elixir', 'erlang', 'haskell',
    'ocaml', 'fsharp', 'csharp', 'dotnet', 'vbnet', 'cobol', 'fortran', 'pascal',
    'assembly', 'asm', 'nasm', 'masm', 'verilog', 'vhdl', 'matlab', 'octave',
    'julia', 'crystal', 'nim', 'zig', 'vlang', 'racket', 'scheme', 'lisp',
    'prolog', 'smalltalk', 'ada', 'forth', 'awk', 'sed', 'powershell', 'batch',
    # --- компиляторы / сборка / тулчейн ---
    'gcc', 'clang', 'llvm', 'gpp', 'cpp', 'javac', 'kotlinc', 'rustc', 'tsc',
    'make', 'cmake', 'ninja', 'meson', 'autoconf', 'automake', 'autotools',
    'bazel', 'buck', 'scons', 'waf', 'ant', 'gulp', 'grunt', 'webpack', 'vite',
    'rollup', 'esbuild', 'parcel', 'babel', 'eslint', 'prettier', 'linter',
    'debugger', 'gdb', 'lldb', 'valgrind', 'strace', 'perf', 'objdump', 'nm',
    'readelf', 'ldd', 'ldconfig', 'strip', 'ranlib', 'ar', 'as', 'ld',
    # --- базы данных ---
    'mysql', 'mariadb', 'psql', 'postgres', 'postgresql', 'sqlite', 'oracle',
    'mssql', 'mongodb', 'mongo', 'redis', 'memcached', 'cassandra', 'couchdb',
    'couchbase', 'dynamodb', 'neo4j', 'influxdb', 'timescaledb', 'clickhouse',
    'elasticsearch', 'solr', 'rethinkdb', 'cockroachdb', 'etcd', 'consul',
    'database', 'table', 'query', 'select', 'insert', 'update', 'delete', 'join',
    'index', 'schema', 'migration', 'transaction', 'commit', 'rollback', 'cursor',
    'primary', 'foreign', 'constraint', 'trigger', 'procedure', 'view', 'orm',
    # --- веб / серверы ---
    'nginx', 'apache', 'httpd', 'caddy', 'traefik', 'haproxy', 'envoy', 'lighttpd',
    'tomcat', 'jetty', 'gunicorn', 'uwsgi', 'uvicorn', 'hypercorn', 'puma',
    'unicorn', 'passenger', 'php', 'phpfpm', 'wsgi', 'asgi', 'cgi', 'fastcgi',
    'express', 'django', 'flask', 'fastapi', 'rails', 'laravel', 'symfony',
    'spring', 'react', 'angular', 'vue', 'svelte', 'nextjs', 'nuxt', 'gatsby',
    'webpack', 'bootstrap', 'tailwind', 'jquery', 'ajax', 'websocket', 'graphql',
    # --- протоколы / сеть термины ---
    'http', 'https', 'http2', 'http3', 'ftp', 'ftps', 'sftp', 'ssh', 'telnet',
    'smtp', 'imap', 'pop3', 'dns', 'dhcp', 'dnssec', 'ldap', 'kerberos', 'radius',
    'snmp', 'ntp', 'nfs', 'smb', 'cifs', 'samba', 'iscsi', 'rdp', 'vnc', 'x11',
    'ssl', 'tls', 'mtls', 'tcp', 'udp', 'icmp', 'ip', 'ipv4', 'ipv6', 'arp',
    'bgp', 'ospf', 'rip', 'eigrp', 'mpls', 'vlan', 'vxlan', 'gre', 'ipsec',
    'nat', 'pat', 'dmz', 'lan', 'wan', 'vpn', 'proxy', 'gateway', 'router',
    'switch', 'bridge', 'firewall', 'loadbalancer', 'cdn', 'reverse', 'forward',
    'subnet', 'netmask', 'cidr', 'broadcast', 'multicast', 'unicast', 'anycast',
    'port', 'socket', 'packet', 'frame', 'datagram', 'mtu', 'ttl', 'handshake',
    # --- форматы / данные ---
    'json', 'xml', 'yaml', 'yml', 'toml', 'ini', 'csv', 'tsv', 'html', 'css',
    'scss', 'sass', 'less', 'markdown', 'rst', 'latex', 'pdf', 'svg', 'png',
    'jpeg', 'gif', 'webp', 'bmp', 'tiff', 'ico', 'mp3', 'wav', 'flac', 'ogg',
    'mp4', 'mkv', 'avi', 'mov', 'webm', 'protobuf', 'grpc', 'avro', 'parquet',
    'base64', 'hex', 'binary', 'utf8', 'ascii', 'unicode', 'encoding', 'charset',
    # --- безопасность / пентест (твоя тема) ---
    'nmap', 'masscan', 'metasploit', 'msfconsole', 'msfvenom', 'burpsuite',
    'burp', 'sqlmap', 'hydra', 'medusa', 'john', 'hashcat', 'aircrack', 'airmon',
    'airodump', 'aireplay', 'reaver', 'wifite', 'kismet', 'ettercap', 'bettercap',
    'mitmproxy', 'responder', 'bloodhound', 'mimikatz', 'empire', 'cobalt',
    'nikto', 'dirb', 'dirbuster', 'gobuster', 'ffuf', 'wfuzz', 'feroxbuster',
    'wpscan', 'joomscan', 'enum4linux', 'smbclient', 'crackmapexec', 'impacket',
    'netexec', 'evilwinrm', 'chisel', 'ligolo', 'proxychains', 'tor', 'torsocks',
    'yara', 'suricata', 'snort', 'zeek', 'osquery', 'wazuh', 'ossec', 'clamav',
    'fail2ban', 'lynis', 'rkhunter', 'chkrootkit', 'aide', 'tripwire', 'auditd',
    'gpg', 'gnupg', 'openssl', 'certbot', 'letsencrypt', 'keytool', 'ssh-keygen',
    'exploit', 'payload', 'shellcode', 'backdoor', 'rootkit', 'malware', 'ransomware',
    'phishing', 'bruteforce', 'privesc', 'pivot', 'lateral', 'reconnaissance',
    'enumeration', 'vulnerability', 'cve', 'cvss', 'mitre', 'attack', 'defense',
    'firewall', 'ids', 'ips', 'siem', 'soc', 'honeypot', 'sandbox', 'forensics',
    'reverse', 'disassembly', 'debugging', 'fuzzing', 'hardening', 'pentest',
    # --- железо / система ---
    'cpu', 'gpu', 'ram', 'rom', 'ssd', 'hdd', 'nvme', 'sata', 'scsi', 'raid',
    'lvm', 'mdadm', 'zfs', 'btrfs', 'ext4', 'xfs', 'ntfs', 'fat32', 'exfat',
    'bios', 'uefi', 'grub', 'systemd-boot', 'bootloader', 'initramfs', 'initrd',
    'kernel', 'module', 'driver', 'firmware', 'modprobe', 'lsmod', 'insmod',
    'rmmod', 'depmod', 'lspci', 'lsusb', 'lshw', 'dmidecode', 'hwinfo', 'inxi',
    'usb', 'pci', 'pcie', 'gpio', 'i2c', 'spi', 'uart', 'hdmi', 'displayport',
    'ethernet', 'wifi', 'bluetooth', 'nfc', 'gps', 'lora', 'zigbee', 'mqtt',
    'arduino', 'raspberry', 'raspberrypi', 'esp32', 'esp8266', 'stm32', 'fpga',
    # --- виртуализация / облако ---
    'kvm', 'qemu', 'libvirt', 'virsh', 'virtualbox', 'vmware', 'vmware', 'hyperv',
    'xen', 'proxmox', 'esxi', 'vsphere', 'openstack', 'cloudstack', 'ovirt',
    'aws', 'azure', 'gcp', 'digitalocean', 'linode', 'vultr', 'hetzner', 'oracle',
    'cloudflare', 'fastly', 'akamai', 'lambda', 'ec2', 'ecs', 'eks', 'gke', 'aks',
    's3', 'rds', 'iam', 'vpc', 'cloudformation', 'cloudwatch', 'route53',
    'serverless', 'faas', 'paas', 'iaas', 'saas', 'microservice', 'monolith',
    # --- общие IT-термины ---
    'server', 'client', 'host', 'localhost', 'hostname', 'domain', 'subdomain',
    'url', 'uri', 'urn', 'endpoint', 'api', 'rest', 'restful', 'graphql', 'soap',
    'rpc', 'grpc', 'websocket', 'webhook', 'callback', 'middleware', 'backend',
    'frontend', 'fullstack', 'database', 'cache', 'queue', 'broker', 'kafka',
    'rabbitmq', 'activemq', 'nats', 'zeromq', 'pubsub', 'stream', 'batch',
    'root', 'admin', 'administrator', 'superuser', 'user', 'guest', 'anonymous',
    'password', 'passphrase', 'credential', 'login', 'logout', 'signin', 'signup',
    'auth', 'authentication', 'authorization', 'oauth', 'jwt', 'token', 'session',
    'cookie', 'cors', 'csrf', 'xss', 'sqli', 'ssrf', 'rce', 'lfi', 'rfi',
    'config', 'configuration', 'setting', 'preference', 'option', 'parameter',
    'argument', 'flag', 'variable', 'constant', 'environment', 'runtime', 'build',
    'log', 'logfile', 'logging', 'debug', 'verbose', 'trace', 'error', 'warning',
    'info', 'critical', 'fatal', 'exception', 'stacktrace', 'traceback', 'crash',
    'process', 'thread', 'coroutine', 'async', 'await', 'sync', 'parallel',
    'concurrent', 'mutex', 'semaphore', 'lock', 'deadlock', 'race', 'atomic',
    'file', 'folder', 'directory', 'path', 'pathname', 'filename', 'extension',
    'symlink', 'hardlink', 'inode', 'permission', 'owner', 'mount', 'unmount',
    'filesystem', 'partition', 'block', 'sector', 'cluster', 'volume', 'quota',
    'backup', 'restore', 'snapshot', 'clone', 'mirror', 'replicate', 'sync',
    'install', 'uninstall', 'reinstall', 'update', 'upgrade', 'downgrade',
    'remove', 'purge', 'clean', 'cleanup', 'flush', 'reset', 'reboot', 'restart',
    'shutdown', 'poweroff', 'halt', 'suspend', 'hibernate', 'resume', 'wakeup',
    'script', 'shell', 'bash', 'zsh', 'fish', 'ksh', 'csh', 'tcsh', 'dash',
    'terminal', 'console', 'tty', 'pty', 'command', 'commandline', 'cli', 'gui',
    'tui', 'prompt', 'pipe', 'redirect', 'stdin', 'stdout', 'stderr', 'fifo',
    'function', 'method', 'class', 'object', 'instance', 'module', 'package',
    'library', 'framework', 'dependency', 'import', 'export', 'namespace',
    'loop', 'iterator', 'generator', 'recursion', 'callback', 'closure', 'lambda',
    'array', 'list', 'tuple', 'dict', 'dictionary', 'hashmap', 'set', 'stack',
    'string', 'integer', 'float', 'double', 'boolean', 'byte', 'char', 'pointer',
    'reference', 'null', 'nil', 'none', 'void', 'undefined', 'nan', 'infinity',
    'algorithm', 'datastructure', 'complexity', 'recursion', 'sorting', 'hashing',
    'encryption', 'decryption', 'cipher', 'hash', 'checksum', 'signature', 'nonce',
    'compression', 'serialization', 'parsing', 'tokenizer', 'compiler', 'interpreter',
    # --- ОС / дистрибутивы ---
    'linux', 'gnu', 'unix', 'bsd', 'freebsd', 'openbsd', 'netbsd', 'solaris',
    'ubuntu', 'debian', 'kali', 'parrot', 'arch', 'manjaro', 'endeavouros',
    'fedora', 'centos', 'rhel', 'rocky', 'almalinux', 'opensuse', 'suse',
    'mint', 'elementary', 'zorin', 'pop', 'popos', 'gentoo', 'slackware', 'void',
    'alpine', 'nixos', 'guix', 'qubes', 'tails', 'whonix', 'raspbian', 'armbian',
    'windows', 'macos', 'osx', 'android', 'ios', 'chromeos', 'harmonyos',
    'altlinux', 'astra', 'redos', 'rosa', 'basealt',
    # --- десктоп-окружения / графика ---
    'gnome', 'kde', 'plasma', 'xfce', 'lxde', 'lxqt', 'mate', 'cinnamon',
    'budgie', 'deepin', 'pantheon', 'enlightenment', 'i3', 'sway', 'hyprland',
    'bspwm', 'awesome', 'dwm', 'openbox', 'fluxbox', 'wayland', 'xorg', 'x11',
    'compositor', 'wm', 'displaymanager', 'gdm', 'sddm', 'lightdm', 'xdm',
    'mesa', 'vulkan', 'opengl', 'nvidia', 'amd', 'intel', 'radeon', 'nouveau',
    'cuda', 'opencl', 'rocm', 'ffmpeg', 'gstreamer', 'vlc', 'mpv', 'obs',
    # --- Reticulum / mesh (твои проекты) ---
    'reticulum', 'nomadnet', 'lxmf', 'rns', 'rnode', 'meshtastic', 'meshchat',
    'lora', 'meshchatx', 'columba', 'propagation', 'broadcaster', 'destination',
    'transport', 'interface', 'identity', 'announce', 'groupctl', 'installret',
    'heltec', 'nomadnetwork', 'ollama', 'gemma', 'llama', 'mistral', 'qwen',
    # --- мониторинг / прочие утилиты ---
    'neofetch', 'fastfetch', 'screenfetch', 'cowsay', 'figlet', 'lolcat', 'tmux',
    'screen', 'byobu', 'zellij', 'ranger', 'nnn', 'lf', 'yazi', 'mc', 'vifm',
    'bat', 'exa', 'eza', 'lsd', 'fd', 'duf', 'ncdu', 'dust', 'procs', 'bottom',
    'zoxide', 'starship', 'ohmyzsh', 'ohmyposh', 'powerlevel', 'antigen', 'zinit',
    'ssh', 'mosh', 'autossh', 'sshfs', 'rclone', 'restic', 'borg', 'duplicity',
    'cron', 'systemd', 'anacron', 'logrotate', 'rsyslog', 'syslog', 'journald',
}
